version: '3.4'

volumes:
  crypto-investment-db:

services:
  redis:
    image: redis:7.0
    ports:
      - '6380:6379'

  db:
    image: postgres:16
    command: -c fsync=off
    volumes:
      - crypto-investment-db:/var/lib/postgresql
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=crypto-investment
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d crypto-investment"]
      interval: 10s
      timeout: 5s
      retries: 5

  app: 
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - '3333:3000'
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379
